sudo: required

env:
  - DaGdConfigFile: config.dev.php

services:
  - docker

before_script:
  - pushd container
  - docker-compose up
  - popd

script:
  - ./tests/dagd_test_suite.php http://localhost:8080

branches:
  only:
    - master

notifications:
  webhooks: https://sl.da.gd/travisci?channel=%23dagd
