sudo: required

env:
  - DaGdConfigFile: config.dev.php

services:
  - docker

before_script:
  - pushd container
  - docker-compose up -d
  - popd

script:
  - while [[ ! -f .ready-for-ci ]]; do echo 'waiting for docker-compose to spin up'; sleep 1; done
  - ./tests/dagd-test -u http://localhost:8080

branches:
  only:
    - master

notifications:
  webhooks:
    if: type != cron
    urls:
      - https://sl.da.gd/travisci?channel=%23dagd
