---
name: dagd-test
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Start docker-compose
        run: pushd container && docker-compose up -d && popd

      - name: Wait for database initialization
        run: |
          while [[ ! -f .ready-for-ci ]]; do
            echo 'waiting for docker-compose to spin up'
            sleep 1
          done

      - name: Run dagd-test
        env:
          DaGdConfigFile: ../container/config.container.php
        run: ./tests/dagd-test -u http://localhost:8080

  notify:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    # If we get a non-cron success, report it
    # If we ever get anything other than success, report it
    - if:
        (needs.build.result == 'success' &&
          github.event_name != 'schedule') ||
        needs.build.result != 'success'
      name: Notify
      uses: joelwmale/webhook-action@master
      with:
        body: '{"channel": "#dagd", "username": "${{ github.repository }}",
          "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          "text": "dagd-test
          status: ${{ needs.build.result }}"}'
        headers: '{"repository": "${{ github.repository }}"}'
        url: https://sl.da.gd/slackjack
