---
name: dagd-test
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Start docker-compose
        run: pushd container && docker-compose up -d && popd

      - name: Wait for database initialization
        run: |
          while [[ ! -f .ready-for-ci ]]; do
            echo 'waiting for docker-compose to spin up'
            sleep 1
          done

      - name: Run dagd-test
        env:
          DaGdConfigFile: ../container/config.container.php
        run: ./tests/dagd-test -u http://localhost:8080

      # We should extend dagd-test to cover CLI stuff, but for now we test
      # dagd-admin separately as part of CI.
      - name: Run dagd-admin tests
        env:
          DaGdConfigFile: ../container/config.container.php
        run: |
          docker exec container_app_1 ./scripts/dagd-admin  -s g | grep State | grep enabled
          docker exec container_app_1 ./scripts/dagd-admin  -s g | grep "defaulting to \-\-status"
          docker exec container_app_1 ./scripts/dagd-admin  -s g -d | grep "Updated in"
          docker exec container_app_1 ./scripts/dagd-admin  -s g | grep State | grep disabled
          docker exec container_app_1 ./scripts/dagd-admin  -s g -e | grep "Updated in"
          docker exec container_app_1 ./scripts/dagd-admin  -s g | grep State | grep enabled
          docker exec container_app_1 ./scripts/dagd-admin  -s g -r https://wikipedia.org/ | grep "Updated in"
          docker exec container_app_1 ./scripts/dagd-admin  -s g -S | grep wikipedia
          docker exec container_app_1 ./scripts/dagd-admin  -s g -r https://google.com/ | grep "Updated in"
